# Generated by Django 2.2.4 on 2019-09-12 15:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_1_value', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_2_value', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_3_value', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='IssueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_1_value', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_2_value', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_3_value', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_full', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'спецпроект',
                'verbose_name_plural': 'спецпроекты',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('project', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
            options={
                'verbose_name': 'выпуск',
                'verbose_name_plural': 'выпуски',
            },
        ),
    ]
