# Generated by Django 2.2.4 on 2019-09-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190913_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuedetail',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.Issue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
