# Generated by Django 2.2.4 on 2019-09-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190913_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-date'], 'verbose_name': 'выпуск', 'verbose_name_plural': 'выпуски'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
