# Generated by Django 2.2.4 on 2019-09-16 06:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190913_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
    ]
